version: '3.9'

volumes:
  app:
  db:

services:
  build:
    build:
      context: ./App42PaaS
    volumes:
      - app:/app/App42PaaS/target:rw

  prod:
    image: tomcat:9-jdk11-slim
    ports:
      - "8090:8080"
    volumes:
      - app:/usr/local/tomcat/webapps:rw
    depends_on:
      - db
      - build

  db:
    image: postgres:9.6.9-alpine
    volumes:
      - db:/var/lib/mysql
    ports:
      - '5432:5432'
    environment:
      - app42.paas.db.username=app42paas
      - app42.paas.db.port=5432
      - app42.paas.db.password=app42paas
      - app42.paas.db.ip=db
      - app42.paas.db.name=app42paas-api