version: '3.9'
services:
  build_App42PaaS:
    build:
      context: ./App42PaaS
    volumes:
      - my_volume:/app/App42PaaS-Java-MySQL-Sample/target

  prod:
    image: tomcat:9-jdk11-slim
    ports:
      - "8090:8080"
    volumes:
      - my_volume:/usr/local/tomcat/webapps

volumes:
  my_volume: