version: '3.9'

volumes:
  app:
  db:

services:
  build:
    build:
      context: ./App42PaaS
    volumes:
      - app:/app/App42PaaS-Java-MySQL-Sample/target:rw

  prod:
    image: tomcat:9-jdk11-slim
    ports:
      - "8090:8080"
    volumes:
      - app:/usr/local/tomcat/webapps:rw
    depends_on:
      - db
      - build

  db:
    image: mariadb:10.1
    volumes:
      - ./mysql:/var/lib/mysql
      - db:/var/lib/mysql